// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lRlGyCzVqXknX7cqhEGlXGa8jiuymFk',
    appId: '1:629377883482:web:9615958f8f160e2c32e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    authDomain: 'donation-app-cc600.firebaseapp.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    measurementId: 'G-WVVYNYEGQ6',
    databaseURL: "https://donation-app-cc600-default-rtdb.firebaseio.com/",


  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_61rxstm1OGimJitaWwbHOdPO9h-HTA0',
    appId: '1:629377883482:android:4dad34307669727e32e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvowuglaBDhT2dN0QxYFjLQjlBjmpPRGg',
    appId: '1:629377883482:ios:d2874c2391b25a7b32e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    iosBundleId: 'com.example.fypDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvowuglaBDhT2dN0QxYFjLQjlBjmpPRGg',
    appId: '1:629377883482:ios:d2874c2391b25a7b32e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    iosBundleId: 'com.example.fypDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7lRlGyCzVqXknX7cqhEGlXGa8jiuymFk',
    appId: '1:629377883482:web:b73e65456bea33b532e763',
    messagingSenderId: '629377883482',
    projectId: 'donation-app-cc600',
    authDomain: 'donation-app-cc600.firebaseapp.com',
    storageBucket: 'donation-app-cc600.firebasestorage.app',
    measurementId: 'G-ZCPPZ10VJ8',
  );
}
